name: driver
description: "An application for transferring orders and goods"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  shared_preferences: ^2.5.2
  country_code_picker: ^3.2.0
  percent_indicator: ^4.2.4
  flutter_dotted: ^0.0.4
  google_maps_flutter: ^2.10.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  firebase_database: ^11.3.2
  firebase_analytics: ^11.4.2
  iconsax: ^0.0.8
  http: ^1.3.0
  audioplayers: ^6.1.2
  firebase_storage: ^12.4.4
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  dio: ^5.8.0+1
  pin_code_fields: ^8.0.1
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  lottie: ^3.1.2
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  location: ^7.0.1
  json_to_model: ^3.0.1
  quiver: ^3.0.1+1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  flutter_polyline_points: ^2.1.0
  google_places_flutter: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
#    - assets/maps/night_map_style.json
    - assets/images/icons/
    - assets/images/
    - assets/sounds/
    - assets/fonts/
    - assets/maps/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
flutter_intl:
  enabled: true
