// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XMqFSKPnWbppM0EF_D3ERwSPNB4yT-E',
    appId: '1:919686196437:web:04a3e458d6f525e6cb865c',
    messagingSenderId: '919686196437',
    projectId: 'driver-e6192',
    authDomain: 'driver-e6192.firebaseapp.com',
    storageBucket: 'driver-e6192.firebasestorage.app',
    measurementId: 'G-17JMGNQ1WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbzyeozBzhTIZv4gXnwRKOkmetTUMg84',
    appId: '1:919686196437:android:f7ed468ff4d6f0bbcb865c',
    messagingSenderId: '919686196437',
    projectId: 'driver-e6192',
    storageBucket: 'driver-e6192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYI3NSNacWplIojzscLeShJRjEcop_RxQ',
    appId: '1:919686196437:ios:a0a0dd331d01577bcb865c',
    messagingSenderId: '919686196437',
    projectId: 'driver-e6192',
    storageBucket: 'driver-e6192.firebasestorage.app',
    iosClientId: '919686196437-36uc1bf7jac2bs1u9fj71pc8rn7fvi4a.apps.googleusercontent.com',
    iosBundleId: 'com.driver.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYI3NSNacWplIojzscLeShJRjEcop_RxQ',
    appId: '1:919686196437:ios:a0a0dd331d01577bcb865c',
    messagingSenderId: '919686196437',
    projectId: 'driver-e6192',
    storageBucket: 'driver-e6192.firebasestorage.app',
    iosClientId: '919686196437-36uc1bf7jac2bs1u9fj71pc8rn7fvi4a.apps.googleusercontent.com',
    iosBundleId: 'com.driver.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XMqFSKPnWbppM0EF_D3ERwSPNB4yT-E',
    appId: '1:919686196437:web:1056553ab33859b5cb865c',
    messagingSenderId: '919686196437',
    projectId: 'driver-e6192',
    authDomain: 'driver-e6192.firebaseapp.com',
    storageBucket: 'driver-e6192.firebasestorage.app',
    measurementId: 'G-Z1PDG3CP7K',
  );
}
